from src.utils.fileutils import FileUtils

APP_DATA_FOLDER_NAME = "app_data"
KEYS_FOLDER_NAME = "keys"
TELEGRAM_BOT_TOKEN_FILE_NAME = "telegram_bot_token.json"
TELEGRAM_SUBSCRIBED_CHAT_IDS_FILE_NAME = "telegram_subscribed_chat_ids.json"
TELETHON_API_INFO_FILE_NAME = "telethon_api_info.json"
TELETHON_NEWS_CHANNELS_INFO_FILE = "telethon_news_channels_info.json"

FOLLOWED_NEWS_GROUP_1_FILE_NAME = "followed_news_group_1.json"

GPT_PROMPT_FILE_NAME = "gpt_prompt.json"

APP_DATA_FOLDER_PATH = FileUtils.join_paths(FileUtils.current_directory(), APP_DATA_FOLDER_NAME)
KEYS_FOLDER_PATH = FileUtils.join_paths(APP_DATA_FOLDER_PATH, KEYS_FOLDER_NAME)
TELEGRAM_BOT_TOKEN_FILE_PATH = FileUtils.join_paths(KEYS_FOLDER_PATH, TELEGRAM_BOT_TOKEN_FILE_NAME)
TELEGRAM_SUBSCRIBED_CHAT_IDS_FILE_PATH = FileUtils.join_paths(APP_DATA_FOLDER_PATH, TELEGRAM_SUBSCRIBED_CHAT_IDS_FILE_NAME)

TELETHON_API_INFO_FILE_PATH = FileUtils.join_paths(KEYS_FOLDER_PATH, TELETHON_API_INFO_FILE_NAME)
TELETHON_NEWS_CHANNELS_INFO_FILE_PATH = FileUtils.join_paths(APP_DATA_FOLDER_PATH, TELETHON_NEWS_CHANNELS_INFO_FILE)

FOLLOWED_NEWS_GROUP_1_FILE_PATH = FileUtils.join_paths(APP_DATA_FOLDER_PATH, FOLLOWED_NEWS_GROUP_1_FILE_NAME)

GPT_PROMPT_FILE_PATH = FileUtils.join_paths(APP_DATA_FOLDER_PATH, GPT_PROMPT_FILE_NAME)
